name: Publish Packages
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm i
            - run: npm t

    publish:
        name: Publish or Create Pull Request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: '@mjefi'
            - name: Install Dependencies
              run: npm i
            - name: Create Release Pull Request or Publish to npm
              uses: changesets/action@master
              with:
                  publish: npm run publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
